import '../bookings_detail_page_one_screen/widgets/diamondfacialcomponentlist_item_widget.dart';import 'package:flutter/material.dart';import 'package:home_services/core/app_export.dart';import 'package:home_services/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:home_services/widgets/app_bar/appbar_title.dart';import 'package:home_services/widgets/app_bar/custom_app_bar.dart';import 'package:home_services/widgets/custom_elevated_button.dart';class BookingsDetailPageOneScreen extends StatelessWidget {const BookingsDetailPageOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 19.v), child: Padding(padding: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("22nd", style: CustomTextStyles.titleMediumBold), SizedBox(height: 2.v), Text("Nov, Tuesday", style: CustomTextStyles.titleMediumBold), SizedBox(height: 12.v), _buildDiamondFacialComponentList(context), SizedBox(height: 24.v), _buildCancelStack(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 84.v, leadingWidth: 61.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgClock, margin: EdgeInsets.only(left: 16.h, top: 27.v, bottom: 12.v), onTap: () {onTapClock(context);}), centerTitle: true, title: AppbarTitle(text: "Upcoming Booking")); } 
/// Section Widget
Widget _buildDiamondFacialComponentList(BuildContext context) { return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: 2, itemBuilder: (context, index) {return DiamondfacialcomponentlistItemWidget();}); } 
/// Section Widget
Widget _buildBillingDetailsColumn(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("Billing Details", style: CustomTextStyles.titleMediumSFProDisplay)), SizedBox(height: 18.v), _buildItemDiscountRow(context, itemDiscountText: "Item Total", priceText: "₹699"), SizedBox(height: 9.v), _buildItemDiscountRow(context, itemDiscountText: "Item Discount", priceText: "-₹50"), SizedBox(height: 9.v), _buildItemDiscountRow(context, itemDiscountText: "Service Fee", priceText: "₹50"), SizedBox(height: 33.v), _buildItemDiscountRow(context, itemDiscountText: "Grand Total", priceText: "₹749")])); } 
/// Section Widget
Widget _buildCancelStack(BuildContext context) { return SizedBox(height: 386.v, width: 343.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 16.v), _buildBillingDetailsColumn(context), SizedBox(height: 15.v), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.customBorderBL10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("Payment mode", style: CustomTextStyles.bodyMediumGray900)), Padding(padding: EdgeInsets.only(top: 3.v), child: Text("Paytm UPI", style: CustomTextStyles.titleSmallMedium))]))]))), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgFrameBlack900, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v), child: Text("Home", style: CustomTextStyles.titleSmallMedium))]), SizedBox(height: 4.v), Container(width: 230.h, margin: EdgeInsets.only(left: 30.h, right: 50.h), child: Text("Plot no.209, Kavuri Hills, Madhapur, Telangana 500033, Ph: +91234567890", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallSFProDisplayGray60001.copyWith(height: 1.50))), SizedBox(height: 8.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgFrameBlack90020x20, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h, top: 4.v), child: Text("Sat, Apr 09 - 07:30 PM", style: CustomTextStyles.bodySmallSFProDisplayGray60001))])]))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(top: 232.v, bottom: 107.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomElevatedButton(text: "Cancel", margin: EdgeInsets.only(right: 6.h), buttonStyle: CustomButtonStyles.fillBlack, buttonTextStyle: CustomTextStyles.titleSmallSFProDisplayOnPrimary, onPressed: () {onTapCancel(context);})), Expanded(child: CustomElevatedButton(text: "Reschedule", margin: EdgeInsets.only(left: 6.h), buttonTextStyle: CustomTextStyles.titleSmallSFProDisplayOnPrimary, onPressed: () {onTapReschedule(context);}))])))])); } 
/// Common widget
Widget _buildItemDiscountRow(BuildContext context, {required String itemDiscountText, required String priceText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(itemDiscountText, style: CustomTextStyles.bodyMediumGray900.copyWith(color: appTheme.gray900)), Text(priceText, style: CustomTextStyles.bodyMediumGreen400.copyWith(color: appTheme.green400))]); } 
/// Navigates to the bookingsUpcomingContainerScreen when the action is triggered.
onTapClock(BuildContext context) { Navigator.pushNamed(context, AppRoutes.bookingsUpcomingContainerScreen); } 
/// Navigates to the cancelBookingScreen when the action is triggered.
onTapCancel(BuildContext context) { Navigator.pushNamed(context, AppRoutes.cancelBookingScreen); } 
/// Navigates to the bookingsDetailPageTwoScreen when the action is triggered.
onTapReschedule(BuildContext context) { Navigator.pushNamed(context, AppRoutes.bookingsDetailPageTwoScreen); } 
 }
