import 'package:flutter/material.dart';import 'package:home_services/core/app_export.dart';import 'package:home_services/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:home_services/widgets/app_bar/appbar_title.dart';import 'package:home_services/widgets/app_bar/custom_app_bar.dart';import 'package:home_services/widgets/custom_elevated_button.dart';import 'package:home_services/widgets/custom_radio_button.dart';import 'package:home_services/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class CancelBookingScreen extends StatelessWidget {CancelBookingScreen({Key? key}) : super(key: key);

String radioGroup = "";

List<String> radioList = ["msg_a_reason_here_for", "msg_a_reason_here_for2", "msg_a_reason_here_for", "msg_a_reason_here_for2"];

TextEditingController commentController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 20.v), child: Column(children: [SizedBox(height: 21.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildDiamondFacialRow(context), SizedBox(height: 24.v), _buildReasonForCancelColumn(context), SizedBox(height: 17.v), _buildGroup328RadioGroup(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: CustomTextFormField(controller: commentController, hintText: "Describe a problem / comment", hintStyle: CustomTextStyles.bodyMediumGray500, textInputAction: TextInputAction.done, maxLines: 8))]))))])), bottomNavigationBar: _buildCancelNowButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 61.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgClock, margin: EdgeInsets.only(left: 16.h, top: 5.v, bottom: 5.v), onTap: () {onTapClock(context);}), centerTitle: true, title: AppbarTitle(text: "Cancel Booking")); } 
/// Section Widget
Widget _buildDiamondFacialRow(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.all(14.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Row(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.max, children: [CustomImageView(imagePath: ImageConstant.imgImage23100x100, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(14.h)), Padding(padding: EdgeInsets.only(left: 16.h, top: 12.v, bottom: 25.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Diamond Facial", style: theme.textTheme.titleSmall), SizedBox(height: 8.v), Row(children: [Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.symmetric(vertical: 6.v), decoration: BoxDecoration(color: appTheme.gray60001, borderRadius: BorderRadius.circular(2.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("2 hrs", style: theme.textTheme.bodyMedium))]), SizedBox(height: 3.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.gray60001, borderRadius: BorderRadius.circular(2.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("Includes dummy info", style: theme.textTheme.bodyMedium))])]))])); } 
/// Section Widget
Widget _buildReasonForCancelColumn(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.fillGray, child: Text("reason for cancellation".toUpperCase(), style: CustomTextStyles.labelLargeInterGray60001Bold)); } 
/// Section Widget
Widget _buildGroup328RadioGroup(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(children: [Padding(padding: EdgeInsets.only(right: 16.h), child: CustomRadioButton(text: "A reason here for cancellation of booking", value: radioList[0], groupValue: radioGroup, onChange: (value) {radioGroup = value;})), Padding(padding: EdgeInsets.only(top: 14.v), child: CustomRadioButton(text: "A reason here for cancellation of booking, a reason here for cancellation of booking  ", value: radioList[1], groupValue: radioGroup, onChange: (value) {radioGroup = value;})), Padding(padding: EdgeInsets.only(top: 13.v, right: 16.h), child: CustomRadioButton(text: "A reason here for cancellation of booking", value: radioList[2], groupValue: radioGroup, onChange: (value) {radioGroup = value;})), Padding(padding: EdgeInsets.only(top: 14.v), child: CustomRadioButton(text: "A reason here for cancellation of booking, a reason here for cancellation of booking  ", value: radioList[3], groupValue: radioGroup, onChange: (value) {radioGroup = value;}))]))); } 
/// Section Widget
Widget _buildCancelNowButton(BuildContext context) { return CustomElevatedButton(text: "Cancel Now", margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 36.v), buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.bodyLargeGray60002); } 
/// Navigates to the bookingsDetailPageOneScreen when the action is triggered.
onTapClock(BuildContext context) { Navigator.pushNamed(context, AppRoutes.bookingsDetailPageOneScreen); } 
 }
