import 'package:flutter/material.dart';import 'package:home_services/core/app_export.dart';import 'package:home_services/widgets/custom_elevated_button.dart';class BookingsUpcomingPage extends StatefulWidget {const BookingsUpcomingPage({Key? key}) : super(key: key);

@override BookingsUpcomingPageState createState() =>  BookingsUpcomingPageState();

 }
class BookingsUpcomingPageState extends State<BookingsUpcomingPage> with  AutomaticKeepAliveClientMixin<BookingsUpcomingPage> {@override bool get wantKeepAlive =>  true;

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillOnPrimary, child: Column(children: [SizedBox(height: 15.v), _buildUpcomingBooking(context)])))); } 
/// Section Widget
Widget _buildUpcomingBooking(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 16.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillBlue5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("22nd", style: CustomTextStyles.titleMedium18), Padding(padding: EdgeInsets.only(top: 3.v), child: Text("Salon for Woman", style: CustomTextStyles.titleSmallMedium))]), SizedBox(height: 2.v), Text("Nov, Tuesday", style: CustomTextStyles.titleMedium18)]), SizedBox(height: 13.v), Row(children: [Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.symmetric(vertical: 6.v), decoration: BoxDecoration(color: appTheme.gray60001, borderRadius: BorderRadius.circular(2.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("Diamond Facial", style: theme.textTheme.bodyMedium))]), SizedBox(height: 5.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.gray60001, borderRadius: BorderRadius.circular(2.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("Cleanup", style: theme.textTheme.bodyMedium))]), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(right: 36.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 156.h, text: "Reshedule", buttonTextStyle: CustomTextStyles.titleSmallSFProDisplayOnPrimary), GestureDetector(onTap: () {onTapTxtViewDetails(context);}, child: Padding(padding: EdgeInsets.only(top: 15.v, bottom: 14.v), child: Text("View details", style: CustomTextStyles.titleSmallPrimary)))]))])); } 
/// Navigates to the bookingsDetailPageOneScreen when the action is triggered.
onTapTxtViewDetails(BuildContext context) { Navigator.pushNamed(context, AppRoutes.bookingsDetailPageOneScreen); } 
 }
